########################################### MySQL 사용하기
spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        #show_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/modudogcat?serverTimezone=Asia/Seoul
    username: ${MD_MYSQL_ID}
    password: ${MD_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

########################################### H2 사용하기
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    hibernate:
#      ddl-auto: create  # (1) 스키마 자동 생성
#    show-sql: true      # (2) SQL 쿼리 출력
#    properties:
#      hibernate:
#        format_sql: true  # (3) SQL pretty print
#  sql:
#    init:
#      data-locations: classpath*:db/h2/data.sql
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: DEBUG
server:
  servlet:
    encoding:
      force-response: true
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 400
  refresh-token-expiration-minutes: 4200
config:
  domain: http://localhost:8080
  adminId: ${ADMIN_ID}
    # ${ADMIN_ID} -> 환경변수를 일단 "admin"으로 등록